
```{r, echo=FALSE}
library(htmltools)
```

```{r, echo=FALSE}
    div(class="row",
      div(class="col-sm-3",
        div(
          class="list-group",
          a(
            class="list-group-item",
            "Tutorials: ANOVA",
            href="Tutorials/ANOVA"
          ),
          a(
            class="list-group-item",
            "Tutorials: Data Frames",
            href="Tutorials/Data Frames"
          ),
          a(
            class="list-group-item",
            "Tutorials: Numerical Descriptives",
            href="Tutorials/Numerical Descriptives"
          ),
          a(
            class="list-group-item",
            "Tutorials: Intro to R",
            href="Tutorials/Intro to R"
          ),
          a(
            class="list-group-item",
            "Tutorials: t Tests",
            href="Tutorials/t Tests"
          ),
          a(
            class="list-group-item",
            "Tutorials: Correlation and Regression",
            href="Tutorials/Correlation and Regression"
          ),
          a(
            class="list-group-item",
            "PSYC: R Dataset Cleaning",
            href="PSYC_Tutorials/R Dataset Cleaning/"
          ),
          a(
            class="list-group-item",
            "PSYC: R Functions",
            href="PSYC_Tutorials/R Functions/"
          ),
          a(
            class="list-group-item",
            "PSYC: R Subsetting",
            href="PSYC_Tutorials/R Subsetting/"
          ),
          a(
            class="list-group-item",
            "PSYC: Vectors",
            href="PSYC_Tutorials/R Vectors/"
          )
        ),
      ),
      div(
        class="col-sm-9",
        h2("BSOS R Tutorials"),
        p("Welcome to the BSOS R Tutorials collection. Here you can find links to R tutorials. They are on the left sidebar, or, if you're using a small screen, they are above.")
      )
    )



```
